// src/lib/components/Button.svelte
<script lang="ts">
	import classNames from 'classnames';

	export let type: 'button' | 'submit' = 'button';
	export let fullWidth = false;
	export let disabled = false;

	let customClassNames = '';
	export { customClassNames as class };

	let className = classNames(
		customClassNames,
		'bg-black px-5 py-3 text-base font-medium text-center text-white bg-primary-700 rounded-lg hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 sm:w-auto dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800',
		{
			'w-full': fullWidth,
			'!cursor-not-allowed !opacity-50 !bg-gray-700 !text-white': disabled,
		}
	);
</script>

<button {type} class={className} disabled={disabled} on:click>
		<slot />
</button>

// src/components/Button.tsx
import cn from 'classnames';
import { MouseEventHandler, ReactNode } from 'react';

type Button = {
  type?: "button" | "submit" | "reset";
  className?: string;
  children: ReactNode;
  onClick?: MouseEventHandler;
};


export default function Button({type, className, children, onClick}:Button) {
  
  return (
    <button
      type={type}
      className={cn(
        className,
        'transition duration-200 text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5',
      )}
    >
      {children}
    </button>
  );
}
