// src/routes/(auth)/login/+page.svelte
<script lang="ts">
  import { newForm } from '@whizzes/svelte-forms';
  import * as Yup from 'yup';

  import { createHeader } from '$lib/utils/basic-auth';

  const { handleSubmit, values } = newForm({
    initialValues: {
      email: '',
      password: ''
    },
    validationSchema: Yup.object({
      email: Yup.string().email().required(),
      password: Yup.string().required()
    }),
    onSubmit: async ({ email, password }) => {
      const basicAuth = createHeader(email, password);
      const response = await fetch('/login', {
        method: 'POST',
        headers: {
          Authorization: basicAuth
        }
      });

      if (response.ok) {
        window.location.pathname = '/';
      }
    }
  });
</script>

<div class="flex flex-1 flex-col items-center justify-center px-10 relative">
  <div class="flex justify-between items-center w-full py-4">
    <div class="flex items-center justify-start space-x-3">
      <span class="bg-black rounded-full w-6 h-6" />
      <a href="https://whizzes.io" class="font-medium text-lg"
        >Whizzes.io + Linx</a
      >
    </div>
    <div class="flex items-center space-x-2">
      <span>Not a member? </span>
      <a href="/signup" class="underline font-medium text-[#070eff]">
        Create an account
      </a>
    </div>
  </div>
  <div class="flex flex-1 flex-col  justify-center space-y-5 max-w-md">
    <div class="flex flex-col space-y-2 text-center">
      <h2 class="text-3xl md:text-4xl font-bold">Sign in to account</h2>
      <p class="text-md md:text-xl">Sign in to access all your data!</p>
    </div>
    <form class="flex flex-col max-w-md space-y-5" on:submit={handleSubmit}>
      <label for="email">Email</label>
      <input
        type="email"
        name="email"
        class="flex px-3 py-2 md:px-4 md:py-3 border-2 border-black rounded-lg font-medium placeholder:font-normal"
        placeholder="E.g. user@email.com"
        bind:value={$values.email}
      />
      <label for="password">Password</label>
      <input
        type="password"
        name="password"
        class="flex px-3 py-2 md:px-4 md:py-3 border-2 border-black rounded-lg font-medium placeholder:font-normal"
        bind:value={$values.password}
      />
      <button
        type="submit"
        class="flex items-center justify-center flex-none px-3 py-2 md:px-4 md:py-3 border-2 rounded-lg font-medium border-black bg-black text-white"
        >Sign in</button
      >
    </form>
  </div>
</div>

// src/components/Login.tsx
import { useState } from 'react';
import Button from './Button';
import ErrorCard from './ErrorCard';
import Input from './Input';

export default function Login() {
  const [error, setError] = useState(null);
  const [credentials, setCredentials] = useState({
    email: '',
    password: '',
  });
  const handleSubmit = async (e:any) => {
    e.preventDefault();

    console.log(credentials);
  };

  return (
      <div className="h-screen flex justify-center flex-col bg-slate-50">
        <div className="w-1/1 sm:w-1/2 lg:w-1/3 m-auto p-6 bg-white rounded-md shadow-lg">
          <h1 className="text-center text-2xl">Login</h1>
          <hr className="my-3" />
          <form onSubmit={handleSubmit}>
            <label htmlFor="email">Email</label>
            <Input
              name="email"
              type="email"
              id="email"
              className="block my-2.5 w-full"
              required
              placeholder="example@example.com"
              onChange={(e:any) => {
                setCredentials({
                  ...credentials,
                  email: e.target.value,
                });
              }}
            />
            <label htmlFor="password">Password</label>
            <Input
              name="password"
              type="password"
              id="password"
              className="block my-2.5 w-full"
              required
              placeholder="password"
              onChange={(e:any) => {
                setCredentials({
                  ...credentials,
                  password: e.target.value,
                });
              }}
            />
            <div className="flex justify-between">
              <a
                href="/signup"
                className="text-base text-blue-500 cursor-pointer"
              >
                Sign up
              </a>
            </div>
            <Button className="mr-2 mt-3 mb-2 w-full" type="submit" onClick={(()=>{})}>
              Login
            </Button>
          </form>
          <ErrorCard error={error} setError={setError} />
        </div>
      </div>
  );
}
