// src/lib/components/TextField.svelte
<script lang="ts">
  import classNames from "classnames";

	export let type: 'text' | 'number' | 'email' | 'password' | 'date' = 'text';
	export let name: string;
	export let id = '';
	export let error: string | null = null;
	export let value: string | number | Date | null = null;
	export let label: string | null = null;
	export let placeholder: string | undefined = undefined;
	export let required = false;
	export let autocomplete: 'true' | 'false' | undefined = undefined;
	let customClassNames = '';
	export { customClassNames as class }
  let className = classNames(customClassNames, 'flex px-3 py-2 md:px-4 md:py-3 border-2 border-black rounded-lg font-medium placeholder:font-normal')
	const handleInput = (event: Event): void => {
		const target = event.target as HTMLInputElement;
		value = type.match(/^(number|range)$/) ? +target.value : target.value;
	};
</script>

	{#if label}
		<label for={name}  class="block font-medium text-gray-700 pb-1"
			>{label}</label
		>
	{/if}
  
		<input
			{name}
			{id}
			{placeholder}
			{required}
			{autocomplete}
			{type}
			{value}
			class:border-red-600={!!error}
			class={className}
			on:change
			on:blur
			on:input={handleInput}
		/>
	<p class:opacity-0={!error} class="text-sm pt-1 text-red-600">{error}</p>

// src/components/TextField.tsx
import classNames from 'classnames';

import type { ChangeEventHandler } from 'react';

type Props = {
  className?: string;
  name: string;
  label: string;
  id?: string;
  type?: 'email' | 'text' | 'password' | 'number';
  placeholder?: string;
  required?: boolean;
  error?: string;
  value: string;
  onChange: ChangeEventHandler | undefined;
};

export default function TextField({
  id,
  name,
  label,
  className,
  placeholder,
  type = 'text',
  required = false,
  error,
  value,
  onChange,
}: Props) {
  const divClassName = classNames('flex flex-col pt-4', className);

  return (
    <div className={divClassName}>
      <label htmlFor={name} className="text-lg">
        {label}
      </label>
      <input
        type={type}
        id={id}
        required={required}
        value={value}
        name={name}
        placeholder={placeholder}
        className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline"
        onChange={onChange}
      />
      <p>{error}</p>
    </div>
  );
}
