// src/routes/(auth)/login/+page.svelte
<script lang="ts">
  import { newForm } from '@whizzes/svelte-forms';
  import * as Yup from 'yup';

  import { createHeader } from '$lib/utils/basic-auth';
  import TextField from '$lib/components/TextField.svelte';
  import Card from '$lib/components/Card.svelte';
  import Button from '$lib/components/Button.svelte';

  const { handleSubmit, values, errors, isSubmitting } = newForm({
    initialValues: {
      email: '',
      password: ''
    },
    validationSchema: Yup.object({
      email: Yup.string().email().required(),
      password: Yup.string().required()
    }),
    onSubmit: async ({ email, password }) => {
      const basicAuth = createHeader(email, password);
      const response = await fetch('/login', {
        method: 'POST',
        headers: {
          Authorization: basicAuth
        }
      });

      if (response.ok) {
        window.location.pathname = '/';
      }
    }
  });
</script>

<div
  class="bg-gray-900 w-full bg-[url('https://demos.creative-tim.com/notus-nextjs/img/register_bg_2.png')] bg-cover"
>
  <div
    class="flex flex-col items-center justify-center px-6 pt-8 mx-auto md:h-screen pt:mt-0 dark:bg-gray-900"
  >
    <a
      href="/"
      class="flex items-center justify-center mb-8 text-2xl text-white font-semibold lg:mb-10 dark:text-white"
    >
      <span>Linx</span>
    </a>
    <Card class="w-full max-w-xl p-6 space-y-8 sm:p-8 dark:bg-gray-800">
      <h2 class="text-2xl font-bold text-gray-900 dark:text-white">
        Sign in to platform
      </h2>
      <form
        class="flex flex-col w-full mt-8 space-y-1"
        on:submit={handleSubmit}
      >
        <TextField
          type="text"
          id="email"
          name="email"
          label="Email"
          placeholder="E.g. user@email.com"
          bind:value={$values.email}
          error={$errors.email}
        />
        <TextField
          type="password"
          id="password"
          name="password"
          label="Password"
          placeholder="• • • • • • • •"
          bind:value={$values.password}
          error={$errors.password}
        />

        <Button type="submit" disabled={$isSubmitting}
          >Login to your account</Button
        >
        <div class="text-sm font-medium text-gray-500 dark:text-gray-400">
          Not registered? <a
            href="/signup"
            class="text-primary-700 hover:underline dark:text-primary-500"
            >Create account</a
          >
        </div>
      </form>
    </Card>
  </div>
</div>

// src/views/login/index.tsx
import { NavLink } from 'react-router-dom';
import { useFormik } from 'formik';
import * as Yup from 'yup';

import Button from '../../components/Button';
import TextField from '../../components/TextField';

export const LoginView: React.FC = () => {
  const formik = useFormik<{
    email: string;
    password: string;
  }>({
    initialValues: {
      email: '',
      password: '',
    },
    validationSchema: Yup.object({
      email: Yup.string().required(),
      password: Yup.string().required(),
    }),
    onSubmit: (values) => {
      console.log(JSON.stringify(values, null, 2));
    },
  });

  return (
    <div className="w-full flex flex-wrap">
      <div className="w-full md:w-1/2 flex flex-col">
        <div className="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
          <p className="text-center text-3xl">Login with your Account</p>
          <form
            className="flex flex-col pt-3 md:pt-8"
            onSubmit={formik.handleSubmit}
          >
            <TextField
              name="email"
              value={formik.values.email}
              label="Email"
              type="email"
              placeholder="john.appleseed@mail.com"
              onChange={formik.handleChange}
            />
            <TextField
              name="password"
              value={formik.values.email}
              label="Password"
              type="password"
              placeholder="Your well kept secret"
              onChange={formik.handleChange}
            />
            <Button className="mt-8">Login</Button>
          </form>
          <div className="text-center pt-12 pb-12">
            <p>
              Don't have an account?{' '}
              <NavLink to="/signup" className="underline font-semibold">
                Create a new one here.
              </NavLink>
            </p>
          </div>
        </div>
      </div>
      <div className="w-1/2 shadow-2xl">
        <img
          alt="illustration"
          className="object-cover w-full h-screen hidden md:block"
          src="https://images.unsplash.com/photo-1668877334122-b60dd15bc1b7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3087&q=80"
        />
      </div>
    </div>
  );
};
